config/routes.rb
Fulcrum::Application.routes.draw do

  get "story/new"

  resources :projects do
    resources :users, :only => [:index, :create, :destroy]
    resources :changesets, :only => [:index]
    resources :stories, :only => [:index, :create, :update, :destroy, :show] do
      resources :notes, :only => [:index, :create, :show, :destroy]
      collection do
        get :done
        get :in_progress
        get :backlog
        get :import
        post :import_upload
      end
      member do
        put :start
        put :finish
        put :deliver
        put :accept
        put :reject
      end
    end
  end

  devise_for :users, :controllers => { 
      :confirmations => "confirmations", 
      :registrations => "registrations"
    }

  match 'testcard' => 'static#testcard'

  root :to => "projects#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  # FIXME - DRY up, repeated in Story model
  JSON_ATTRIBUTES = ["id", "name", "initials", "email"]

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :initials, :email_delivery, :email_acceptance, 
                  :email_rejection, :locale

  # Flag used to identify if the user was found or created from find_or_create
  attr_accessor :was_created

  has_and_belongs_to_many :projects, :uniq => true

  before_validation :set_random_password_if_blank, :set_reset_password_token

  validates :name, :presence => true
  validates :initials, :presence => true

  def to_s
    "#{name} (#{initials}) <#{email}>"
  end

  def set_random_password_if_blank
    if new_record? && self.password.blank? && self.password_confirmation.blank?
      self.password = self.password_confirmation = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{email}--")[0,6]
    end
  end

  def set_reset_password_token
    if new_record?
      self.reset_password_token = Devise.friendly_token
    end
  end

  def as_json(options = {})
    super(:only => JSON_ATTRIBUTES)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :json

  def index
    @project = current_user.projects.find(params[:project_id])
    @users = @project.users
    @user = User.new
    respond_with(@users)
  end

  def create
    @project = current_user.projects.find(params[:project_id])
    @users = @project.users
    @user = User.find_or_create_by_email(params[:user][:email]) do |u|
      # Set to true if the user was not found
      u.was_created = true
      u.name = params[:user][:name]
      u.initials = params[:user][:initials]
    end

    if @user.new_record? && !@user.save
      render 'index'
      return
    end

    if @project.users.include?(@user)
      flash[:alert] = "#{@user.email} is already a member of this project"
    else
      @project.users << @user
      if @user.was_created
        flash[:notice] = "#{@user.email} was sent an invite to join this project"
      else
        flash[:notice] = "#{@user.email} was added to this project"
      end
    end

    redirect_to project_users_url(@project)
  end

  def destroy
    @project = current_user.projects.find(params[:project_id])
    @user = @project.users.find(params[:id])
    @project.users.delete(@user)
    redirect_to project_users_url(@project)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% content_for :title_bar do %>
  <%= render :partial => 'projects/nav', :locals => {:project => @project} %>
<% end %>
<h2>Project members</h2>
<ul>
  <% @users.each do |user| %>
    <li><%= user %><%= link_to 'Remove', project_user_path(@project, user),
      :confirm => "Are you sure you want to remove #{user.email} from this project?",
      :method => :delete %></li>
  <% end %>
</ul>
<h2>Add a new member</h2>
<div class="form-wrapper">
<%= form_for project_users_path(@project, @user) do |f| %>
  <% fields_for :user do |u| %>
    <div class="field-wrapper">
      <%= u.label :email %>
      <div class="field"><%= u.text_field :email %></div>
    </div>
    <div class="field-wrapper">
      <%= u.label :name %>
      <div class="field"><%= u.text_field :name %></div>
    </div>
    <div class="field-wrapper">
      <%= u.label :initials %>
      <div class="field"><%= u.text_field :initials %></div>
    </div>
    <div class="actions">
    <%= u.submit 'Add user' %>
    </div>
  <% end %>
<% end %>
</div>